# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scaffold CSS · Layout Library
description: > # this means to ignore newlines until "baseurl:"
  The 12-column flex grid was a hack. Scaffold CSS embraces native Grid and Flex with utility classes and mixins — just enough structure to get out of your way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scaffoldcss.rehanbutt.com" # the base hostname & protocol for your site

site-version: 1.0.0
library-version: 1.0.0

product-name: Scaffold CSS
github: https://github.com/naher94/scaffoldcss

# Build settings
markdown: kramdown

collections:
  docs:
    output: false
    sort_by: sort
  fun-facts:
    output: false
  features:
    output: false
    sort_by: sort